### ISSUE TITLE
TODO for v2

### ISSUE THREAD

**Issue by esheldon** [esheldon/ngmix#111]
TODO

- [ ] rework most of the bootstrappers, without backwards compatibility
- [ ] remove unused code that probably doesn't even work, e.g. importance samplers, etc.
- [ ]  improve test coverage
- [ ] add pixel level tests for metacal operations

**Comment by esheldon** [comment]
whoops, forgot we already had issues for these things
